mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir1000000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir1000000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir1000000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir1000000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir100000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir10000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir5000000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir5000000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir5000000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir5000000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir500000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir500000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir500000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir500000_RLC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000_RC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000_RC.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000_RLC2.net --pf params.txt
mpirun -n 1 ./miniXyce.x --circuit /mnt/disk1/gjh/circuit_netlist/cir50000_RLC.net --pf params.txt