./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir1000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir5000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir10000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir20000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir30000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir40000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir50000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir60000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir70000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir80000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir90000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir100000.mtx  minixyce 100 2
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir1000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir5000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir10000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir20000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir30000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir40000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir50000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir60000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir70000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir80000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir90000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir100000.mtx  minixyce 100 4
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir1000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir5000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir10000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir20000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir30000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir40000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir50000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir60000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir70000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir80000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir90000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir100000.mtx  minixyce 100 8
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir1000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir5000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir10000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir20000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir30000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir40000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir50000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir60000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir70000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir80000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir90000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir100000.mtx  minixyce 100 16
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir1000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir5000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir10000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir20000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir30000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir40000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir50000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir60000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir70000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir80000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir90000.mtx  minixyce 100 32
./main  /home/liujie/gmres/iSparse/circuit_simulation/miniXyce_1.0-expspmv/miniXyce_ref/cir100000.mtx  minixyce 100 32