./a.out /home/GaoJH/spmv/standard_matrix/bcircuit.mtx
./a.out /home/GaoJH/spmv/standard_matrix/bcsstk17.mtx
./a.out /home/GaoJH/spmv/standard_matrix/Bump_2911.mtx
./a.out /home/GaoJH/spmv/standard_matrix/cell2.mtx
./a.out /home/GaoJH/spmv/standard_matrix/ch7-8-b2.mtx
./a.out /home/GaoJH/spmv/standard_matrix/circuit_1.mtx
./a.out /home/GaoJH/spmv/standard_matrix/coater2.mtx
./a.out /home/GaoJH/spmv/standard_matrix/cryg10000.mtx
./a.out /home/GaoJH/spmv/standard_matrix/ex35.mtx
./a.out /home/GaoJH/spmv/standard_matrix/fe_body.mtx
./a.out /home/GaoJH/spmv/standard_matrix/fxm3_16.mtx
./a.out /home/GaoJH/spmv/standard_matrix/G62.mtx
./a.out /home/GaoJH/spmv/standard_matrix/garon2.mtx
./a.out /home/GaoJH/spmv/standard_matrix/gyro_m.mtx
./a.out /home/GaoJH/spmv/standard_matrix/inlet.mtx
./a.out /home/GaoJH/spmv/standard_matrix/lhr14.mtx
./a.out /home/GaoJH/spmv/standard_matrix/lp_nug12.mtx
./a.out /home/GaoJH/spmv/standard_matrix/lshp3025.mtx
./a.out /home/GaoJH/spmv/standard_matrix/mk10-b2.mtx
./a.out /home/GaoJH/spmv/standard_matrix/n4c6-b5.mtx
./a.out /home/GaoJH/spmv/standard_matrix/nemeth13.mtx
./a.out /home/GaoJH/spmv/standard_matrix/OPF_6000.mtx
./a.out /home/GaoJH/spmv/standard_matrix/reorientation_3.mtx
./a.out /home/GaoJH/spmv/standard_matrix/rosen10.mtx
./a.out /home/GaoJH/spmv/standard_matrix/spaceShuttleEntry_4.mtx
./a.out /home/GaoJH/spmv/standard_matrix/std1_Jac2_db.mtx
./a.out /home/GaoJH/spmv/standard_matrix/tols2000.mtx
./a.out /home/GaoJH/spmv/standard_matrix/TSOPF_RS_b162_c3.mtx
